# With GIT Config
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/iusverma/s-config

# With local files
spring:
  cloud:
    config:
      server:
        native:
          searchLocation: classpath:/config
  profiles:
    active: native