server.port: 8080

# With GIT Config
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iusverma/s-config
        native:
          searchLocation: classpath:/config
  profiles:
    active: native,default

# With local files
#spring:
#  cloud:
#    config:
#      server:
#        native:
#          searchLocation: classpath:/config
#  profiles:
#    active: native